export type Level = "beginner" | "intermediate" | "advanced";

export interface Word {
  id: string;
  word: string;
  phonetic: string;
  partOfSpeech: string;
  meaningKo: string;
  meaningEn: string;
  example: string;
  exampleKo: string;
  level: Level;
}

export const LEVEL_LABELS: Record<Level, string> = {
  beginner: "Beginner (초급)",
  intermediate: "Intermediate (중급)",
  advanced: "Advanced (고급)",
};

export const VOCABULARY: Word[] = [
  // Beginner
  {
    id: "b1",
    word: "apple",
    phonetic: "/ˈæpəl/",
    partOfSpeech: "noun",
    meaningKo: "사과",
    meaningEn: "a round fruit with red, green, or yellow skin",
    example: "She eats an apple every morning.",
    exampleKo: "그녀는 매일 아침 사과를 먹는다.",
    level: "beginner",
  },
  {
    id: "b2",
    word: "run",
    phonetic: "/rʌn/",
    partOfSpeech: "verb",
    meaningKo: "달리다",
    meaningEn: "to move quickly using your legs",
    example: "I run in the park every day.",
    exampleKo: "나는 매일 공원에서 달린다.",
    level: "beginner",
  },
  {
    id: "b3",
    word: "happy",
    phonetic: "/ˈhæpi/",
    partOfSpeech: "adjective",
    meaningKo: "행복한",
    meaningEn: "feeling or showing pleasure",
    example: "She looks very happy today.",
    exampleKo: "그녀는 오늘 매우 행복해 보인다.",
    level: "beginner",
  },
  {
    id: "b4",
    word: "book",
    phonetic: "/bʊk/",
    partOfSpeech: "noun",
    meaningKo: "책",
    meaningEn: "a set of printed pages bound together",
    example: "This book is very interesting.",
    exampleKo: "이 책은 매우 흥미롭다.",
    level: "beginner",
  },
  {
    id: "b5",
    word: "water",
    phonetic: "/ˈwɔːtər/",
    partOfSpeech: "noun",
    meaningKo: "물",
    meaningEn: "a clear liquid without color or taste",
    example: "Please give me a glass of water.",
    exampleKo: "물 한 잔 주세요.",
    level: "beginner",
  },
  {
    id: "b6",
    word: "friend",
    phonetic: "/frend/",
    partOfSpeech: "noun",
    meaningKo: "친구",
    meaningEn: "a person you know well and like",
    example: "He is my best friend.",
    exampleKo: "그는 나의 가장 친한 친구이다.",
    level: "beginner",
  },
  {
    id: "b7",
    word: "eat",
    phonetic: "/iːt/",
    partOfSpeech: "verb",
    meaningKo: "먹다",
    meaningEn: "to put food in your mouth and swallow it",
    example: "We eat dinner at seven.",
    exampleKo: "우리는 7시에 저녁을 먹는다.",
    level: "beginner",
  },
  {
    id: "b8",
    word: "school",
    phonetic: "/skuːl/",
    partOfSpeech: "noun",
    meaningKo: "학교",
    meaningEn: "a place where children go to learn",
    example: "My school is near the park.",
    exampleKo: "우리 학교는 공원 근처에 있다.",
    level: "beginner",
  },

  // Intermediate
  {
    id: "i1",
    word: "achieve",
    phonetic: "/əˈtʃiːv/",
    partOfSpeech: "verb",
    meaningKo: "달성하다, 성취하다",
    meaningEn: "to succeed in reaching a goal",
    example: "She worked hard to achieve her dream.",
    exampleKo: "그녀는 꿈을 이루기 위해 열심히 일했다.",
    level: "intermediate",
  },
  {
    id: "i2",
    word: "consider",
    phonetic: "/kənˈsɪdər/",
    partOfSpeech: "verb",
    meaningKo: "고려하다",
    meaningEn: "to think about something carefully",
    example: "Please consider my offer.",
    exampleKo: "제 제안을 고려해 주세요.",
    level: "intermediate",
  },
  {
    id: "i3",
    word: "environment",
    phonetic: "/ɪnˈvaɪrənmənt/",
    partOfSpeech: "noun",
    meaningKo: "환경",
    meaningEn: "the natural world around us",
    example: "We should protect the environment.",
    exampleKo: "우리는 환경을 보호해야 한다.",
    level: "intermediate",
  },
  {
    id: "i4",
    word: "opportunity",
    phonetic: "/ˌɒpəˈtjuːnəti/",
    partOfSpeech: "noun",
    meaningKo: "기회",
    meaningEn: "a chance to do something",
    example: "This is a great opportunity for you.",
    exampleKo: "이것은 당신에게 큰 기회이다.",
    level: "intermediate",
  },
  {
    id: "i5",
    word: "suggest",
    phonetic: "/səˈdʒest/",
    partOfSpeech: "verb",
    meaningKo: "제안하다",
    meaningEn: "to offer an idea or plan",
    example: "I suggest we leave early.",
    exampleKo: "나는 우리가 일찍 떠날 것을 제안한다.",
    level: "intermediate",
  },
  {
    id: "i6",
    word: "describe",
    phonetic: "/dɪˈskraɪb/",
    partOfSpeech: "verb",
    meaningKo: "묘사하다, 설명하다",
    meaningEn: "to say what something is like",
    example: "Can you describe the man you saw?",
    exampleKo: "당신이 본 그 남자를 묘사할 수 있나요?",
    level: "intermediate",
  },
  {
    id: "i7",
    word: "require",
    phonetic: "/rɪˈkwaɪər/",
    partOfSpeech: "verb",
    meaningKo: "필요로 하다, 요구하다",
    meaningEn: "to need something",
    example: "This job requires a lot of patience.",
    exampleKo: "이 일은 많은 인내를 필요로 한다.",
    level: "intermediate",
  },
  {
    id: "i8",
    word: "available",
    phonetic: "/əˈveɪləbl/",
    partOfSpeech: "adjective",
    meaningKo: "이용 가능한",
    meaningEn: "able to be used or obtained",
    example: "The book is available at the library.",
    exampleKo: "그 책은 도서관에서 이용할 수 있다.",
    level: "intermediate",
  },

  // Advanced
  {
    id: "a1",
    word: "ubiquitous",
    phonetic: "/juːˈbɪkwɪtəs/",
    partOfSpeech: "adjective",
    meaningKo: "어디에나 있는, 편재하는",
    meaningEn: "present, appearing, or found everywhere",
    example: "Smartphones have become ubiquitous in modern life.",
    exampleKo: "스마트폰은 현대 생활에서 어디에나 있게 되었다.",
    level: "advanced",
  },
  {
    id: "a2",
    word: "meticulous",
    phonetic: "/məˈtɪkjələs/",
    partOfSpeech: "adjective",
    meaningKo: "꼼꼼한, 세심한",
    meaningEn: "showing great attention to detail",
    example: "He is meticulous about his work.",
    exampleKo: "그는 자신의 일에 꼼꼼하다.",
    level: "advanced",
  },
  {
    id: "a3",
    word: "ephemeral",
    phonetic: "/ɪˈfemərəl/",
    partOfSpeech: "adjective",
    meaningKo: "덧없는, 순간적인",
    meaningEn: "lasting for a very short time",
    example: "The beauty of cherry blossoms is ephemeral.",
    exampleKo: "벚꽃의 아름다움은 덧없다.",
    level: "advanced",
  },
  {
    id: "a4",
    word: "pragmatic",
    phonetic: "/præɡˈmætɪk/",
    partOfSpeech: "adjective",
    meaningKo: "실용적인",
    meaningEn: "dealing with things in a practical way",
    example: "We need a pragmatic approach to this problem.",
    exampleKo: "우리는 이 문제에 실용적인 접근이 필요하다.",
    level: "advanced",
  },
  {
    id: "a5",
    word: "elaborate",
    phonetic: "/ɪˈlæbərət/",
    partOfSpeech: "adjective",
    meaningKo: "정교한, 상세한",
    meaningEn: "very detailed and complicated",
    example: "She gave an elaborate explanation.",
    exampleKo: "그녀는 상세한 설명을 해주었다.",
    level: "advanced",
  },
  {
    id: "a6",
    word: "resilient",
    phonetic: "/rɪˈzɪliənt/",
    partOfSpeech: "adjective",
    meaningKo: "회복력 있는, 탄력 있는",
    meaningEn: "able to recover quickly from difficulties",
    example: "Children are often resilient in tough times.",
    exampleKo: "아이들은 종종 힘든 시기에 회복력이 있다.",
    level: "advanced",
  },
  {
    id: "a7",
    word: "scrutinize",
    phonetic: "/ˈskruːtənaɪz/",
    partOfSpeech: "verb",
    meaningKo: "면밀히 조사하다",
    meaningEn: "to examine something very carefully",
    example: "The auditor scrutinized every document.",
    exampleKo: "감사관은 모든 문서를 면밀히 조사했다.",
    level: "advanced",
  },
  {
    id: "a8",
    word: "paradigm",
    phonetic: "/ˈpærədaɪm/",
    partOfSpeech: "noun",
    meaningKo: "패러다임, 전형",
    meaningEn: "a typical example or pattern of something",
    example: "This discovery caused a paradigm shift in science.",
    exampleKo: "이 발견은 과학에 패러다임 전환을 가져왔다.",
    level: "advanced",
  },
];
